import { Product, Review } from '@/types/product.types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Classic Cotton T-Shirt',
    price: 15000,
    images: [
      { url: '/products/cover.png', color: 'Black', alt: 'Black T-Shirt' },
      { url: '/products/cover2.png', color: 'White', alt: 'White T-Shirt' },
      { url: '/products/cover3.png', color: 'Blue', alt: 'Blue T-Shirt' },
    ],
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Blue', hex: '#0066CC' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    category: 'Shirts',
    inStock: true,
    description: 'Premium quality cotton t-shirt perfect for everyday wear. Soft, breathable fabric ensures comfort all day long.',
    features: [
      'Premium quality cotton',
      'Versatile wardrobe staple',
      'Comfortable fit',
      'Machine washable',
    ],
    rating: 4.5,
    reviewCount: 24,
    isFeatured: true,
    isBestseller: true,
  },
  {
    id: '2',
    name: 'Cozy Hoodie',
    price: 35000,
    images: [
      { url: '/products/cover6.png', color: 'Grey', alt: 'Grey Hoodie' },
      { url: '/products/cover7.png', color: 'Black', alt: 'Black Hoodie' },
    ],
    colors: [
      { name: 'Grey', hex: '#808080' },
      { name: 'Black', hex: '#000000' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    category: 'Hoodie',
    inStock: true,
    description: 'Stay warm and stylish with our premium hoodie. Features soft fleece lining and adjustable drawstring hood.',
    features: [
      'Fleece-lined interior',
      'Adjustable hood',
      'Kangaroo pocket',
      'Ribbed cuffs and hem',
    ],
    rating: 4.8,
    reviewCount: 45,
    isFeatured: true,
  },
  {
    id: '3',
    name: 'Baseball Cap',
    price: 8000,
    images: [
      { url: '/products/cover3.png', color: 'Red', alt: 'Red Cap' },
      { url: '/products/cover4.png', color: 'Navy', alt: 'Navy Cap' },
    ],
    colors: [
      { name: 'Red', hex: '#FF0000' },
      { name: 'Navy', hex: '#000080' },
    ],
    sizes: ['M', 'L'],
    category: 'Caps',
    inStock: false,
    description: 'Classic baseball cap with adjustable strap. Perfect for casual outings and sun protection.',
    features: [
      'Adjustable strap',
      'Cotton blend',
      'Curved brim',
      'Breathable design',
    ],
    rating: 4.2,
    reviewCount: 18,
  },
  {
    id: '4',
    name: 'Cotton T-Shirt',
    price: 15000,
    images: [
      { url: '/products/cover4.png', color: 'Black', alt: 'Black T-Shirt' },
      { url: '/products/cover5.png', color: 'White', alt: 'White T-Shirt' },
      { url: '/products/cover6.png', color: 'Blue', alt: 'Blue T-Shirt' },
    ],
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Blue', hex: '#0066CC' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    category: 'Shirts',
    inStock: true,
    description: 'Premium quality cotton t-shirt perfect for everyday wear. Soft, breathable fabric ensures comfort all day long.',
    features: [
      'Premium quality cotton',
      'Versatile wardrobe staple',
      'Comfortable fit',
      'Machine washable',
    ],
    rating: 4.5,
    reviewCount: 24,
    isFeatured: true,
    isBestseller: true,
  },
  {
    id: '9',
    name: 'Cozy Hoodie',
    price: 35000,
    images: [
      { url: '/products/cover6.png', color: 'Grey', alt: 'Grey Hoodie' },
      { url: '/products/cover7.png', color: 'Black', alt: 'Black Hoodie' },
    ],
    colors: [
      { name: 'Grey', hex: '#808080' },
      { name: 'Black', hex: '#000000' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    category: 'Hoodie',
    inStock: true,
    description: 'Stay warm and stylish with our premium hoodie. Features soft fleece lining and adjustable drawstring hood.',
    features: [
      'Fleece-lined interior',
      'Adjustable hood',
      'Kangaroo pocket',
      'Ribbed cuffs and hem',
    ],
    rating: 4.8,
    reviewCount: 45,
    isFeatured: true,
  },
  {
    id: '5',
    name: 'Baseball Cap',
    price: 8000,
    images: [
      { url: '/products/cover7.png', color: 'Red', alt: 'Red Cap' },
      { url: '/products/cover8.png', color: 'Navy', alt: 'Navy Cap' },
    ],
    colors: [
      { name: 'Red', hex: '#FF0000' },
      { name: 'Navy', hex: '#000080' },
    ],
    sizes: ['M', 'L'],
    category: 'Caps',
    inStock: false,
    description: 'Classic baseball cap with adjustable strap. Perfect for casual outings and sun protection.',
    features: [
      'Adjustable strap',
      'Cotton blend',
      'Curved brim',
      'Breathable design',
    ],
    rating: 4.2,
    reviewCount: 18,
  },
  {
    id: '6',
    name: 'Classic Cotton T-Shirt',
    price: 15000,
    images: [
      { url: '/products/cover8.png', color: 'Black', alt: 'Black T-Shirt' },
      { url: '/products/cover8.png', color: 'White', alt: 'White T-Shirt' },
      { url: '/products/cover7.png', color: 'Blue', alt: 'Blue T-Shirt' },
    ],
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Blue', hex: '#0066CC' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    category: 'Shirts',
    inStock: true,
    description: 'Premium quality cotton t-shirt perfect for everyday wear. Soft, breathable fabric ensures comfort all day long.',
    features: [
      'Premium quality cotton',
      'Versatile wardrobe staple',
      'Comfortable fit',
      'Machine washable',
    ],
    rating: 4.5,
    reviewCount: 24,
    isFeatured: true,
    isBestseller: true,
  },
  {
    id: '10',
    name: 'Classic Cotton T-Shirt',
    price: 15000,
    images: [
      { url: '/products/cover8.png', color: 'Black', alt: 'Black T-Shirt' },
      { url: '/products/cover8.png', color: 'White', alt: 'White T-Shirt' },
      { url: '/products/cover7.png', color: 'Blue', alt: 'Blue T-Shirt' },
    ],
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Blue', hex: '#0066CC' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    category: 'Shirts',
    inStock: true,
    description: 'Premium quality cotton t-shirt perfect for everyday wear. Soft, breathable fabric ensures comfort all day long.',
    features: [
      'Premium quality cotton',
      'Versatile wardrobe staple',
      'Comfortable fit',
      'Machine washable',
    ],
    rating: 4.5,
    reviewCount: 24,
    isFeatured: true,
    isBestseller: true,
  },
  {
    id: '7',
    name: 'Cozy Hoodie',
    price: 35000,
    images: [
      { url: '/products/cover2.png', color: 'Grey', alt: 'Grey Hoodie' },
      { url: '/products/cover3.png', color: 'Black', alt: 'Black Hoodie' },
    ],
    colors: [
      { name: 'Grey', hex: '#808080' },
      { name: 'Black', hex: '#000000' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    category: 'Hoodie',
    inStock: true,
    description: 'Stay warm and stylish with our premium hoodie. Features soft fleece lining and adjustable drawstring hood.',
    features: [
      'Fleece-lined interior',
      'Adjustable hood',
      'Kangaroo pocket',
      'Ribbed cuffs and hem',
    ],
    rating: 4.8,
    reviewCount: 45,
    isFeatured: true,
  },
  {
    id: '8',
    name: 'Baseball Cap',
    price: 8000,
    images: [
      { url: '/products/cover3.png', color: 'Red', alt: 'Red Cap' },
      { url: '/products/cover4.png', color: 'Navy', alt: 'Navy Cap' },
    ],
    colors: [
      { name: 'Red', hex: '#FF0000' },
      { name: 'Navy', hex: '#000080' },
    ],
    sizes: ['M', 'L'],
    category: 'Caps',
    inStock: false,
    description: 'Classic baseball cap with adjustable strap. Perfect for casual outings and sun protection.',
    features: [
      'Adjustable strap',
      'Cotton blend',
      'Curved brim',
      'Breathable design',
    ],
    rating: 4.2,
    reviewCount: 18,
  },
];

export const mockReviews: Review[] = [
  {
    id: 'r1',
    productId: '1',
    userId: 'u1',
    userName: 'David Jones',
    userImage: undefined,
    rating: 5,
    comment: 'Absolutely love this t-shirt! The fabric is soft and the fit is perfect. Highly recommend!',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'r2',
    productId: '1',
    userId: 'u2',
    userName: 'Sarah Williams',
    userImage: undefined,
    rating: 4,
    comment: 'Great quality for the price. Only wish there were more color options.',
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
  },
];

export const mockStickers = [
  { id: 's1', url: '/stickers/star.svg', name: 'Star' },
  { id: 's2', url: '/stickers/heart.svg', name: 'Heart' },
  { id: 's3', url: '/stickers/lightning.svg', name: 'Lightning' },
  { id: 's4', url: '/stickers/peace.svg', name: 'Peace' },
  { id: 's5', url: '/stickers/crown.svg', name: 'Crown' },
];